### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by femi-saliu** [fiddioteam/fiddio#97]
Includes getting started tutorial, tech stack, grunt commands

**Comment by femi-saliu** [comment]
Also put the link to fidd.io at the top of the repo

**Comment by kamronbatman** [comment]
git clone the repository

install postgres - https://wiki.postgresql.org/wiki/Detailed_installation_guides
For mac development, can use - http://postgresapp.com/

set up postgres database, can use the following for development:
CREATE DATABASE fiddio;
CREATE USER root PASSWORD '';
ALTER USER root with SUPERUSER;

add a file called '.env' with the following:
NODE_ENV    = 'development'

urlAbsolute     = 'fidd.io'
urlAbsoluteDev  = 'localhost:8000'

port            = 80
portDev         = 8000

dbClient        = 'postgres'
dbHost          = '127.0.0.1'
dbUser          = 'root'
dbPassword      = ''
dbDatabase      = 'fiddio'

ghApiIdDev      = ''
ghApiSecretDev  = ''

ghApiId         = ''
ghApiSecret     = ''

fbApiIdDev      = ''
fbApiSecretDev  = ''

fbApiId         = ''
fbApiSecret     = ''

mpApiId     = ''
mpApiSecret   = ''

sessionKey      = 'fiddio'
sessionSecret   = 'we like kitties!'

run 'npm install'

run grunt start to start the server

run grunt stop to stop the background server when in production mode

run grunt build to build the server without running it
